package app.Utility;

public enum EnamActions {
    JOINING_CLAN,
    BATTLES_PAYMENT, BATTLES_WIN, BATTLES_DEDUCT,
    GAMBLES_PAYMENT, GAMBLES_WIN, GAMBLES_DEDUCT,
    RETURN_PAYMENT,
    TASKS, TASKS_DEDUCT,
    HUNTING, HUNTING_DEDUCT
}
